apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  creationTimestamp: null
  name: backend
spec:
  gateways:
  - public-gateway.istio-system
  - mesh
  hosts:
  - backend.mission-control-dev.52.224.90.111.xip.io
  - backend
  http:
  - route:
    - destination:
        host: backend.mission-control-dev.svc.cluster.local
